apiVersion: v1
kind: Pod
metadata:
  name: cccd-template-deploy-migrator
  labels:
    app: cccd-template-deploy-migrator
spec:
  containers:
  - name: cccd-migrator
    imagePullPolicy: Always
    image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-get-paid/cccd:set-me
    env:
      - name: AWS_REGION
        valueFrom:
          secretKeyRef:
            name: cccd-secrets
            key: AWS_REGION
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: cccd-s3-bucket
            key: access_key_id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: cccd-s3-bucket
            key: secret_access_key
      - name: DESTINATION_AWS_S3_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: cccd-s3-bucket
            key: bucket_name
      - name: SOURCE_AWS_REGION
        valueFrom:
          secretKeyRef:
            name: cccd-template-deploy-secrets
            key: AWS_REGION
      - name: SOURCE_AWS_S3_BUCKET_NAME
        valueFrom:
          secretKeyRef:
            name: cccd-template-deploy-secrets
            key: AWS_S3_BUCKET_NAME
      - name: SOURCE_DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: cccd-template-deploy-secrets
            key: DATABASE_URL
      - name: SOURCE_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: cccd-template-deploy-secrets
            key: DATABASE_NAME
      - name: DESTINATION_DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: cccd-rds
            key: url
      - name: DESTINATION_DATABASE_HOST
        valueFrom:
          secretKeyRef:
            name: cccd-rds
            key: rds_instance_address
      - name: DESTINATION_DATABASE_USERNAME
        valueFrom:
          secretKeyRef:
            name: cccd-rds
            key: database_username
      - name: DESTINATION_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: cccd-rds
            key: database_password
      - name: DESTINATION_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: cccd-rds
            key: database_name
