require_relative 'migrator/helpers'
require_relative 'migrator/options'
require_relative 'migrator/commands'
require_relative 'migrator/s3'
require_relative 'migrator/rds'
require_relative 'migrator/exe'
require 'benchmark'
require 'pry-byebug'